### ISSUE TITLE
io.kestra.plugin.jira.issues.Create Bad request error

### ISSUE THREAD

**Issue by kawtar-Mouhib** [kestra-io/plugin-jira#21]
### Describe the issue

Hello , are there any issues with this plugin : io.kestra.plugin.jira.issues.Create  , it seems like it constantly returns "Bad request " , this plugin works properly with the same credentials with no issues : "io.kestra.plugin.jira.issues.CreateComment" . 

Does anyone know why this could be? 

```
tasks:
  - id: create_ticket
    type: io.kestra.plugin.jira.issues.Create
    baseUrl: https://domain.atlassian.net
    username: test@test.com
    password: xxx
    projectKey: LIG
    issuetype: Bug
    projectKey: LIG
    summary: "Workflow failed"
    description: "test issue "
    labels:
      - bug
      - workflow
    issuetype: Bug
```

<img width="1367" alt="Image" src="https://github.com/user-attachments/assets/5c777815-8cb3-4793-97f7-2f8d01ce7a04" />

### Environment

- Kestra Version: develop
