### ISSUE TITLE
Create a task to comment a ticket 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/plugin-jira#3]
```yaml 
id: myflow
namespace: company.myteam

tasks:
  - id: hello
    type: io.kestra.plugin.jira.issues.CreateComment
    baseUrl: your-domain.atlassian.net
    username: your_email@example.com
    password: your_jira_api_token
    projectKey: myproject
    issueIdOrKey: "JIR-123"
    body: "{{ execution.id }} has failed on {{ taskrun.startDate }}"
```
